# Develop branch'ine bir pull request merge'lendiginde, develop branchini master brancine merge'ler
name: Merge to master

on: 
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # with:
      #   token: ${{ github.token }}
    - name: Set Git config
      run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
    - name: Merge develop -> master
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: develop
        target_branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: print token
      run: ${{ secrets.GITHUB_TOKEN }}
    # - name: Merge master back to dev
    #   run: |
    #       git fetch origin
    #       git checkout master
    #       git pull origin master
    #       git merge --no-ff develop -m "Auto-merge develop to master"
    #       git push origin master