# Develop branch'ine bir pull request merge'lendiginde, develop branchini master brancine merge'ler
name: Merge to master

on: 
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        # token: ${{ github.token }}
    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: Set Git config
      run: |
          git config user.name "actions"
          git config user.email "github-actions@github.com"
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Merge master back to dev
      run: |
          git fetch origin
          git checkout master
          git pull origin master --allow-unrelated-histories
          git merge --no-ff develop -m "Auto-merge develop to master" --allow-unrelated-histories
          git push origin master


    # - name: Opening pull request
    #   id: pull
    #   uses: tretuna/sync-branches@1.4.0
    #   with:
    #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    #     FROM_BRANCH: "develop"
    #     TO_BRANCH: "master"

    # - name: Merge develop -> master
    #   uses: devmasx/merge-branch@master
    #   with:
    #     type: now
    #     from_branch: develop
    #     target_branch: master
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    # - name: print token
    #   run: ${{ secrets.GITHUB_TOKEN }}
